name: "QA"

on:
    push:
        branches:
            - master

permissions:
    pull-requests: write
    contents: read

jobs:
    qa:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3
                if: ${{ steps.check-secrets.outputs.ok == 'true' }}
            -   name: set up JDK 11
                uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3
                if: ${{ steps.check-secrets.outputs.ok == 'true' }}
                with:
                    distribution: "temurin"
                    java-version: 11
            -   name: Install NDK and cmake
                if: ${{ steps.check-secrets.outputs.ok == 'true' }}
                run: |
                    source ndk.env
                    /usr/local/lib/android/sdk/tools/bin/sdkmanager "ndk;${NDK_VERSION}" "cmake;${CMAKE_VERSION}"
            -   name: Build QA
                if: ${{ steps.check-secrets.outputs.ok == 'true' }}
                run: |
                    mkdir -p $HOME/.gradle
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > $HOME/.gradle/gradle.properties
                    sed -i "/qa/,/\}/ s/versionCode .*/versionCode ${{github.event.number}} /" app/build.gradle
                    sed -i "/qa/,/\}/ s/versionName .*/versionName \"${{github.event.number}}\"/" app/build.gradle
                    ./gradlew assembleQaDebug

            - name: Upload APK
              uses: actions/upload-artifact@v2
              with:
                  name: qa-debug-${{github.event.number}}
                  path: app/build/outputs/apk/qa/debug/qa-debug-*.apk